/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myContractSol from "./MyContract.sol";
export type { myContractSol };
export type { TokenERC20 } from "./TokenERC20";
